gameLibrary = {
    'gravwell': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'citadels': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'lovecraft_letter': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'love_letter': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'avalon': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'draculas_feast':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'sequence':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'clue':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'ticket_to_ride': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'catan': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'mysterium': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'betrayal_at_house_on_the_hill': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'dominion': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'libertalia': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'lords_of_waterdeep': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'cup_of_bluff': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'hive':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'tsuro': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'dixit': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'spheres_of_influence': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'sentinels_of_the_multiverse': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'alchemists':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'stealth_chess': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'parcheesi': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'five_kings':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'welcome_to_the_dungeon': {
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'inn_fighting':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'mille_borne':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'werewords':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'munchkin':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'strain':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'red_november':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'sherrif_of_nottingham':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'betrayal_at_baldurs_gate':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'upwords':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'cant_stop':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'dos':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'gloom':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'dark_tales':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'once_upon_a_time':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'racko':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'uno':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'the_crew':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'dragon_farkle':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'fairytale_gloom':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'coup':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'star_fluxx':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'pirate_fluxx':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'the_mind':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'splendor':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'cryptid':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'perpetual_commotion':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'chess':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'checkers':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'backgammon':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'exploding_kittens':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    },
    'think_str8':{
    'players': int,
    'time': int,
    'fiddly_bits': 'y/n',
    'weight': 'light/medium/heavy',
    'strategy': 'light/medium/heavy',
    'player_relation': 'coop/competitive',
    'play_mechanic': 'str',
    }
};

print(gameLibrary['alchemists']['players']);